### ISSUE TITLE
PHPMD vs PHPCS

### ISSUE THREAD

**Issue by phptek** [chillu/phpmd-silverstripe#2]
Wouldn't coding-standards _specific_ functionality viz a viz SilverStripe coding guidelines be better suited or implemented in a PHPCS module for Silverstripe? Because PHPCS allows for auto-correcting code, this lends itself well to IDE-specific configuration via this module.

So for example I might want to offer-up a Netbeans 8.0+ config for PHPCS and others could do the same for PHPStorm, PHP Eclipse (Does that still exist?) Sublime etc.

**Comment by phptek** [comment]
@chillu the observation above still stands with reference to http://phpqatools.org/

**Comment by phptek** [comment]
Not enough coffee leads to bad choices in button pressing...

**Comment by chillu** [comment]
Hey Russ, thanks for the feedback! Yeah, auto-fixing would be fantastic. Both PHPMD and PHPCS perform checks, only PHPCS supports rewriting the code. So this would become effectively a separate project to implement SilverStripe rules as PHPCS checks, separate from this PHPMD focused solution. 

I've also gotten a bit confused between the fact that there's two "CS" solutions out there:
 * PHP CodeSnipper (by Squiz): https://github.com/squizlabs/PHP_CodeSniffer/
 * PHP Coding Standards Checker (by Symfony): http://cs.sensiolabs.org/ (details: https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master)
Looks like both can run checks only as well, and both are extensible. I'm inclined to give the Symfony one a try since it's newer and looks easier to write.

In the context of SilverStripe Code Reviews, we obviously can't rewrite code - so there's not going to be much momentum to get this implemented as part of this stream of work. My next step is just getting devs here using PHPMD and see how well it is received. Do you have any plans to implement CS checks?

**Comment by phptek** [comment]
@chillu at the moment no. I'm evaluating phpmd and its integration into phpStorm (Yes, I have finally made the switch away from NetBeans) given that this is what the rest of the guys use. Once I can come up with a usable SilverStripe related ruleset (yours, or based off yours) then I'l be attempting to ensure we all use the same IDE config.

I also noticed SS uses the EditorConfig formatting system, something else I'm keen to integrate into the IDE - yeah there's a plugin, just need to tweak the file and configure the IDE properly.
